name: Check Devices JSON
on:
  push:
    branches:
      - eleven
  pull_request:
    branches:
      - eleven
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: validate
        uses: anyone-developer/anyone-validate-json@main
        with:
          file-extension: ".json"
          ignore-files: "README.md"
          ignore-directories: ".git"
          read-path: "devices"
